# Generated by Django 5.2.13 on 2026-05-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firebase_uid',
            new_name='supabase_uid',
        ),
    ]
