# Generated by Django 5.2.13 on 2026-05-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_firebase_uid_user_supabase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('front', models.FloatField(blank=True, db_column='Front', null=True)),
                ('front_and_back', models.FloatField(blank=True, db_column='Front_and_back', null=True)),
                ('digital_cover_300g', models.FloatField(blank=True, db_column='Digital_Cover_300g', null=True)),
                ('digital_cover_200g', models.FloatField(blank=True, db_column='Digital_Cover_200g', null=True)),
                ('offset_cover_200g', models.FloatField(blank=True, db_column='Offset_Cover_200g', null=True)),
                ('offset_cover_300g', models.FloatField(blank=True, db_column='Offset_Cover_300g', null=True)),
                ('coil_size_10', models.FloatField(blank=True, db_column='Coil_size_10', null=True)),
                ('coil_size_12', models.FloatField(blank=True, db_column='Coil_size_12', null=True)),
                ('coil_size_14', models.FloatField(blank=True, db_column='Coil_size_14', null=True)),
                ('coil_size_16', models.FloatField(blank=True, db_column='Coil_size_16', null=True)),
                ('coil_size_18', models.FloatField(blank=True, db_column='Coil_size_18', null=True)),
                ('coil_size_20', models.FloatField(blank=True, db_column='Coil_size_20', null=True)),
                ('coil_size_22', models.FloatField(blank=True, db_column='Coil_size_22', null=True)),
                ('coil_size_25', models.FloatField(blank=True, db_column='Coil_size_25', null=True)),
                ('coil_size_28', models.FloatField(blank=True, db_column='Coil_size_28', null=True)),
                ('coil_size_30', models.FloatField(blank=True, db_column='Coil_size_30', null=True)),
                ('coil_size_32', models.FloatField(blank=True, db_column='Coil_size_32', null=True)),
                ('coil_size_35', models.FloatField(blank=True, db_column='Coil_size_35', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pricing', to='api.user')),
            ],
            options={
                'db_table': 'Pricing',
            },
        ),
    ]
