# Generated by Django 5.2.13 on 2026-05-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cover_file',
        ),
        migrations.RemoveField(
            model_name='item',
            name='content_file',
        ),
        migrations.RemoveField(
            model_name='item',
            name='preview_file',
        ),
        migrations.RemoveField(
            model_name='item',
            name='package',
        ),
        migrations.RemoveField(
            model_name='order',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='package',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='user',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
