# Generated by Django 5.2.13 on 2026-05-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('completed_quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_step', models.CharField(choices=[('pending', 'Pending'), ('design', 'Design'), ('printing', 'Printing'), ('cutting', 'Cutting'), ('packaging', 'Packaging'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=50)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
    ]
