# Generated by Django 5.2.13 on 2026-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('file_type', models.CharField(choices=[('cover', 'Cover'), ('content', 'Content'), ('preview', 'Preview'), ('package_image', 'Package Image')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
    ]
