# Generated by Django 5.2.13 on 2026-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_uid', models.CharField(max_length=128, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('owner', 'Owner'), ('staff', 'Staff')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
